### ISSUE TITLE
TypeScript + Module system

### ISSUE THREAD

**Issue by nikeee** [mdaines/viz.js#127]
I am planning to use Viz.js in Node and in the browser, using TypeScript.
The 2.0.0 Usage states:
https://github.com/mdaines/viz.js/wiki/2.0.0-Usage

When running node:
```JavaScript
const Viz = require('viz.js');
const { Module, render } = require('viz.js/full.js.opaque');
```

In the browser:
```JavaScript
import Viz from 'viz.js';
import worker from 'viz.js/full.js.opaque';
```

The second version looks like ES modules. However, if I compile this with TypeScript (`tsc --module es6 a.ts`), I get therse errors:
```
a.ts(1,17): error TS2307: Cannot find module 'viz.js'.
a.ts(2,20): error TS2307: Cannot find module 'viz.js/full.js.opaque'.
```
The resulting JS looks like the TypeScript source.

If I run it without `--module es6` (so that non-es-module code gets emitted), I get these compiler errors:
```
a.ts(1,8): error TS1192: Module '"/mnt/x/node_modules/viz.js/index"' has no default export.
a.ts(2,20): error TS2307: Cannot find module 'viz.js/full.js.opaque'.
```

And this is the compiler output:
```JavsAcript
"use strict";
exports.__esModule = true;
var viz_js_1 = require("viz.js");
var full_js_opaque_1 = require("viz.js/full.js.opaque");
var viz = new viz_js_1["default"]({ worker: full_js_opaque_1["default"] });
```

If I run this in Node.js, I get this error: `TypeError: viz_js_1.default is not a constructor`

The defaut exports do not seem to work. Is there any way to use viz.js as a ES module? Maybe I am using the wrong compiler switches. It would simplify the build process for me and would be awesome, since node and browser usage were the same for me.

**Comment by mdaines** [comment]
It looks like there are a couple problems with the TypeScript declarations I've written. I'll have a fix for that soon.

The usage example with the import statements is intended for bundlers like Rollup or Webpack that allow for importing files as paths in the final bundle rather than bindings. The reason for the odd `.js.opaque` name is to indicate that the bundler shouldn't look inside that file. You'll get an error if you import one of the `.js.opaque` files and try to use it for the `worker` option.

You'll probably want to do something like this instead: (when the TypeScript stuff is working properly)

```js
import Viz from 'viz.js';
import { Module, render } from 'viz.js/full.js.opaque';

let viz = new Viz({ Module, render });
```

**Comment by mdaines** [comment]
I've decided to remove the TypeScript declarations from this repository. I don't use TypeScript, and I don't have time to maintain them. If by any chance you're interested in working on this, you are of course welcome to contribute declarations for Viz.js to DefinitelyTyped.
