### ISSUE TITLE
Image support in v3

### ISSUE THREAD

**Issue by lucafabbian** [mdaines/viz.js#191]
Old forks like [this one](https://github.com/aduh95/viz.js) provided support for image embedding. As far as I can tell, this feature is long gone. Am I right?

If you are ok with that, I may try to implement it myself and provide a pull request.

**Comment by mdaines** [comment]
This feature is in the v2 branch (added in https://github.com/mdaines/viz-js/commit/5e0a451eb0955e417a6155522e8e1a149ae101e6), but obviously that hasn't had a release in a while. When preparing v3 earlier this year, I decided to omit it, mainly because including filesystem support increases the bundle size. The feature also depends on a series of hacks around Graphviz image handling, and I was hoping to eventually find some way to support images that doesn't require creating dummy images at paths that kind of look like URLs, etc.

I'm curious to know more about the situation in which you're using images and how well the API from v2 would work for you.

Also, I'm not sure what this would look like, but I imagine there's some change or enhancement to Graphviz that could make this easier to implement.

**Comment by lucafabbian** [comment]
As you may have seen, I've made a fork + pull request that restores the feature. It's working, even though it still relies on the same hacks of v2 and also includes a small hack due to an emscripten bug. 


In the past, I used another port of graphviz (called hpcc-js) on my project [Magebook](magebook.github.io), which is an editor for interactive fiction that started as a university project and ended up being employed by several writers in Italy.
Writers may tag book chapters and scenes with flag images, and it would be nice if those were shown in the book graph as well.

I could not use the v2 because I need some features from graphviz 8.
I've already switched to my fork, and I'm happy with that. I just thought this may be an important feature for others as well.

As far as I understand, the file size increase is negligible (from 1.363mb to 1.402mb for the viz-standalone.js).

**Comment by mdaines** [comment]
> Writers may tag book chapters and scenes with flag images, and it would be nice if those were shown in the book graph as well.

How would you refer to the images in your project? And is the SVG meant to be used outside of Magebook? (It looks like there's a download link?) The example in your PR uses a full URL, but I can imagine wanting `<image>` elements in the SVG output to use a path for `href`, like `/picsum.photos/id/184/100/100` or `./100`. It would also be nice if data URLs could be used.

I'm wondering about other approaches as well. I have a project in which I'd like to be able to use something like the SVG `<foreignObject>` element.

> As far as I understand, the file size increase is negligible (from 1.363mb to 1.402mb for the viz-standalone.js).

I should have checked myself; for some reason I thought it was much larger.

> I just thought this may be an important feature for others as well.

I agree, so given that the size increase is not so bad, I'll look at bringing this to a future release.

**Comment by jcody42** [comment]
Curious if this had been reviewed and if the size increase will be prohibitive. Having image support will greatly improve my  use case. Thanks!

**Comment by Neriderc** [comment]
Just commenting to add that I'm also keen for image support in the new version. Still using the previous release from 5 or 6 years ago in the meantime.

**Comment by mdaines** [comment]
~I've started a draft PR to add support for this here: #232~

PR to add support here: #233
