### ISSUE TITLE
Question about usage without Webassembly and some other questions

### ISSUE THREAD

**Issue by aglasencnik** [mdaines/viz.js#230]
Hi, I have a couple of questions, someone might know the answer to...
Basically the first question is: Do I need to use webassembly to run this library? Because it says it is a webassembly build... And I want to execute the code in c# with the Jint library. Basically, could I run the library as in a normal browser...
Second: In the viz-standalone.js there are a lot of "random" characters... what is that?
Third: Do I need to include your license if I want to create my own library for c# out of your library? I would include your "compiled" source code in my library...
Thanks

**Comment by mdaines** [comment]
First question: I'm not entirely sure, but based on a quick look, Jint doesn't appear to support WebAssembly. Therefore, this library won't work in that environment. At some point, it has to call `WebAssembly.instantiate()`.

Second question: the WebAssembly binary produced by Emscripten is encoded as base64 and bundled with the Viz.js JavaScript wrapper. This allows the library to be distributed as a single file.

Third question: my view is that if you distribute software that includes Viz.js, you need to include a copy of the license. You would also be distributing "object code" of Graphviz and Expat, so you should check on the licenses for those projects as well.

Maybe this isn't an option, and obviously I don't know the details of your project, but I would consider [using Graphviz as a library](https://www.graphviz.org/docs/library/) rather than bundling this project. You might be able to get help with using it from C# on the [Graphviz forum](https://forum.graphviz.org).
