### ISSUE TITLE
Status of the viz-js OSS project

### ISSUE THREAD

**Issue by another-guy** [mdaines/viz.js#255]
I saw [this comment](https://github.com/mdaines/viz-js/issues/69#issuecomment-256556460) dated 2016 which says that the project is "frozen". The Contributors activity chart, however, shows there is some activity starting Q1 2023 all the way till time of writing this GitHub issue.

What is the official status of viz-js? Are PRs still welcome or the users are on their own and forking is a good approach if we need new features?

Thank you! 🙏🙏🙏

cc @mdaines 

![image](https://github.com/user-attachments/assets/491850dc-b8c2-4b43-9c93-8735660e6334)

**Comment by mdaines** [comment]
I didn't have time to work on Viz.js for a while, and eventually archived the GitHub project and deprecated the npm package. Recently I picked it up again and released a new version that targets WASM, and have been generally keeping up with Graphviz releases.

As for the particular issue you linked, it looks like `class` attributes were added for SVG output in Graphviz about a year earlier, so Viz.js may have been using an old version of Graphviz at that point.

In general, I don't think Viz.js should add features to Graphviz. And it's better to contribute to that project if possible, because more people can benefit.

If you have a feature request or bug fix specifically for Viz.js, please open an issue or PR.
