### ISSUE TITLE
Cannot enlarge memory arrays. Probably memory leak?

### ISSUE THREAD

**Issue by p1o2p3u1** [mdaines/viz.js#45]
I use websocket to draw graphs dynamically using viz.js. However when the Viz function is called too much times it will throw the following error
```javascript
Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.") at Error
    at jsStackTrace (http://localhost:8889/static/js/viz.js:5:22063)
    at stackTrace (http://localhost:8889/static/js/viz.js:5:22246)
    at abort (http://localhost:8889/static/js/viz.js:28:10646)
    at enlargeMemory (http://localhost:8889/static/js/viz.js:5:22596)
    at Function.Runtime.dynamicAlloc [as alloc] (http://localhost:8889/static/js/viz.js:5:6520)
    at _sbrk (http://localhost:8889/static/js/viz.js:5:604858)
    at A1 (http://localhost:8889/static/js/viz.js:20:81202)
    at rK (http://localhost:8889/static/js/viz.js:12:187893)
    at qK (http://localhost:8889/static/js/viz.js:12:187625)
    at dg (http://localhost:8889/static/js/viz.js:11:139350)
``` 

You can open your Chrome console and run the following code and it will give you the same error message
```javascript
for(var i=0; i<5000; i++){Viz("digraph { a -> b; }");}
```

**Comment by mdaines** [comment]
Thanks for reporting this. The Viz.js wrapper code wasn't freeing memory allocated by the Graphviz library. This is addressed in 425313ec8cc637d685088412c5db81198ca76041 and I'll post a release shortly.

**Comment by mdaines** [comment]
https://github.com/mdaines/viz.js/releases/tag/1.0.1

**Comment by innovimax** [comment]
I just got the same issue today

Error: InternalError: uncaught exception: abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ") at jsStackTrace@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:20800 stackTrace@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:20983 abort@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:28:5424 abortOnCannotGrowMemory@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:21343 enlargeMemory@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:21788 Module/Runtime.dynamicAlloc@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:6269 _sbrk@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:602577 M4@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:21:7406 P4@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:21:19271 sF@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:9:178843 hF@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:9:174584 nF@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:9:176587 Ud@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:11:65882 Nd@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:11:59924 uR@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:10:139781 II@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:13:103660 gI@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:13:66228 uJ@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:13:146116 _H@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:13:60223 EH@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:13:37406 KH@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:13:47922 bG@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:9:204789 dc@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:11:857 ccallFunc@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:5:8075 Viz@http://mdaines.github.io/viz.js/bower_components/viz.js/viz.js:54:25 onmessage@http://mdaines.github.io/viz.js/worker.js:4:16 If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

**Comment by mdaines** [comment]
@innovimax, it looks like this happened using the Viz.js demo page. Do you mind posting the graph you used? Did you run into this over many changes to the graph?
