### ISSUE TITLE
Support HTML tags in labels

### ISSUE THREAD

**Issue by jdavey** [mdaines/viz.js#55]
```
digraph g{ 
568910544 [label=<root<sub>pd</sub>>,shape=ellipse,fillcolor="lightblue",style="filled"];
} 
```

In the graph viz app, this will be rendered correctly, but not with this the viz.js library

**Comment by mdaines** [comment]
What is the correct rendering of this graph?

Here's what I get from the Graphviz command-line tool: (dot - graphviz version 2.38.0 (20140413.2041))

![test dot](https://cloud.githubusercontent.com/assets/1383/11431583/56ae8734-9469-11e5-88d7-21371950ec9b.png)

Here's what I get from Viz.js:

<img src="https://cloud.githubusercontent.com/assets/1383/11431584/5d4f6702-9469-11e5-8887-446fdc8883de.png" width="107" height="59">

(Rendered using http://mdaines.github.io/viz.js/)

The second seems more correct to me since it respects the `<sub>` tag.

**Comment by NawfelBgh** [comment]
cc me.

**Comment by jdavey** [comment]
I actually have the opposite behavior (subscripted node using GVEdit, non-subscripted with viz.js), but it may be related to how I am displaying it in my application.

I'm using the angular directive ng-bind-html which seems to render it without the subscript. However, as you have pointed it, doing in your demo app or in a singular webpage it renders correctly so I don't think this is a Viz.js issue.

**Comment by aquaalex** [comment]
@jdavey maybe close this item, it does not look like a viz.js issues
