### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by pvnr0082t** [mdaines/viz.js#67]
Hi @mdaines ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we found that license info different between cdnjs and the repo.
Because the license info is not very precise, could you please point out the license the repo used from the following:
- "0BSD"
- "BSD-2-Clause-FreeBSD"
-  "BSD-2-Clause-NetBSD"
-  "BSD-2-Clause"
-  "BSD-3-Clause-Attribution"
-  "BSD-3-Clause-Clear"
-  "BSD-3-Clause-LBNL"
-  "BSD-3-Clause"
-  "BSD-4-Clause-UC"
-  "BSD-4-Clause"
- "BSD-Protection"

Thank you.

https://github.com/cdnjs/cdnjs/issues/8527

**Comment by BigBlueHat** [comment]
It's actually released under the [The Unlicense](http://unlicense.org/)--a form of public domain dedication. See the [SPDX info on The Unlicense](https://spdx.org/licenses/Unlicense.html).

It's not in the Open Source Initiative's list of [approved (by that organization) licenses](https://opensource.org/licenses/alphabetical)...but then neither is [CC0](https://creativecommons.org/choose/zero/).

Perhaps the OSI doesn't list it because it's not technically a license, but a public domain dedication.

Regardless, it's not BSD-* 😃
