### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by magjac** [mdaines/viz.js#81]
The text overflows the bound box.

![screenshot from 2017-04-06 08 30 35](https://cloud.githubusercontent.com/assets/6350376/24740819/5974fc52-1aa3-11e7-8b9b-64b6460dc122.png)

```
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  </head>
  <body>
    <div id="viz">
    </div>
    <script src="bower_components/graphviz-d3-renderer/lib/viz.js/viz.js"></script>
    <script>
    var dotSrc = `
        strict digraph {
            graph [fontsize=20.0 labelloc=t rankdir=BT]
            node [fontname="Liberation Sans" fontsize=14
                  margin=0 shape=box style=filled]
                    "SAND-53" [label="This text is 31 characters long"
                         color="#000000" fillcolor="#f6c342"
                         fontcolor="#000000" shape=box style=filled]
    }
`
    var svgData = Viz(dotSrc);
    svg1 = document.getElementById("viz");
    svg1.innerHTML = svgData;
    </script>
  </body>
</html>
```
If the fontname attribute is removed, the overflow does not occur.

The problem occurs for:
Mozilla Firefox 48.0 on Ubuntu 14.04.5 LTS
Google Chrome Version 57.0.2987.110 (64-bit) on Ubuntu 14.04.5 LTS
Firefox 52.0.1 (32-bit) on Windows 7
Google Chrome Version 56.0.2924.87 (64-bit) on Windows 7.

This issue has been spawned from https://github.com/mstefaniuk/graphviz.it/issues/14

It does not occur if the svg is generated directly with graphviz 2.38.0:

dot -Tsvg viz.js.bug.dot > viz.js.bug.svg

![screenshot from 2017-04-06 08 33 17](https://cloud.githubusercontent.com/assets/6350376/24740896/b4d964b6-1aa3-11e7-804d-6e68a1f4ba19.png)

```
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  </head>
  <body>
    <div id="viz">
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041)
 -->
<!-- Title: %3 Pages: 1 -->
<svg width="197pt" height="44pt"
 viewBox="0.00 0.00 197.00 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
<title>%3</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-40 193,-40 193,4 -4,4"/>
<!-- SAND&#45;53 -->
<g id="node1" class="node"><title>SAND&#45;53</title>
<polygon fill="#f6c342" stroke="#000000" points="189,-36 0,-36 0,-0 189,-0 189,-36"/>
<text text-anchor/="middle" x="94.5" y="-14.3" font-family="Liberation Sans" font-size="14.00" fill="#000000">This text is 31 characters long</text>
</g>
</g>
</svg>
    </div>
  </body>
</html>
```

**Comment by mdaines** [comment]
My guess is that since Viz.js doesn't have access to the Liberation Sans font to measure the text, Graphviz is falling back on its own font metrics, but is including the name of the font in the generated SVG anyway. Then, since you do have that font on your system, your browser is using it when rendering the SVG.

**Comment by magjac** [comment]
Thanks. Can I give Viz.js access to the font somehow?

**Comment by mdaines** [comment]
Not at this time. It might be possible, but it would probably require Graphviz being able to access the font files at least. I am looking at adding more access to the Emscripten file system.

Another approach might be to measure the size of the box yourself before passing it to Viz.js, but I don't know if that would actually work in this situation.

**Comment by tdhsmith** [comment]
As opposed to fixing fontconfig / filesystem stuff, the browser could certainly determine the glyph and text widths using a `<canvas>` and [`CanvasRenderingContext2D.measureText()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/measureText). Does this library do anything to patch/shim Graphviz for special web features, or would that be new ground? (I don't have much experience with Emscripten yet, so I'm not sure the terminology is here.)

It's messy, but I'm assuming you could straight up replace `textspan.c` methods pre-compilation with ones that can call the web API through something like `EM_ASM_DOUBLE`?

Just some thoughts, since the problem was fairly annoying to me this morning.

**Comment by mdaines** [comment]
@tdhsmith That would be new ground for Viz.js, since for the most part I've tried to not reach too far inside Graphviz -- the idea is that using the interface it expects will lead to fewer surprises down the line. However, if you do explore that approach, a pull request is welcome!

I mentioned this briefly above, and maybe it's something you'd be willing to try. (I haven't, so I don't know how well it will work.) Determine the measurements of the nodes yourself, specify the height and width of the nodes explicitly and use blank labels, and then add the text to the SVG after getting the output. One thing this depends on is being able to find the nodes in the SVG, but you can assign `id` attributes to them.

For example:

```dot
digraph {
  a[width=2,height=1,label="",id="a"];
  b[width=1,height=1,label="",id="b"];
    
  a -> b;
}
```

In the SVG output, the dimensions of the ellipses are 144x72 and 72x72 points, inside group elements with ids "a" and "b".

**Comment by tdhsmith** [comment]
@mdaines Yeah I totally agree with the arguments; you don't want to destabilize anything or ruin your ability to pull in upstream content.

I'll bet determining measurements would work fine (in fact for our use case with HTML-like labels, I don't even need to take the label out because the child `<table>` still autosizes correctly), but I think we're fine just having switched out monospace font to Courier.
